const mongoose = require("mongoose");

const areas = [
  "Bedok",
  "Bukit Timah",
  "Bukit Batok",
  "Bukit Merah",
  "Central Water Catchment",
  "Downtown Core",
  "Changi",
  "Changi Bay",
  "Lim Chu Kang",
  "Boon Lay",
  "Western Water Catchment",
  "Woodlands",
  "Marine Parade",
  "Newton",
  "North-Eastern Island",
  "Orchard",
  "Pasir Ris",
  "Pioneer",
  "Punggol",
  "Queenstown",
  "Sembawang",
  "Simpang",
  "Tampines",
  "Tanglin",
  "Tuas",
  "Western Islands",
  "Southern Islands",
  "Bukit Panjang",
  "Bishan",
  "Ang Mo Kio",
  "Geylang",
  "Straits View",
  "Jurong East",
  "Hougang",
  "Jurong West",
  "Choa Chu Kang",
  "Kallang",
  "Mandai",
  "Tengah",
  "Marina East",
  "Marina South",
  "Museum",
  "Novena",
  "Outram",
  "Paya Lebar",
  "River Valley",
  "Rochor",
  "Seletar",
  "Sengkang",
  "Serangoon",
  "Clementi",
  "Toa Payoh",
  "Singapore River",
  "Sungei Kadut",
  "Yishun",
];

const MerchantSchema = new mongoose.Schema({
  name: { type: String, require: true },
  address: { type: String, require: true },
  area: { type: String, enum: areas, require: true },
  coordinates: { type: String },
  description: { type: String, require: true },
});

const AuthSchema = new mongoose.Schema({
  email: { type: String, require: true },
  hash: { type: String, require: true },
  account_type: {
    type: String,
    enum: ["user", "merchant"],
    require: true,
    default: "user",
  },
  merchant_details: MerchantSchema,
});

module.exports = mongoose.model("Auth", AuthSchema);
